fix(focus): remove code from last PR that was breaking focus on interruption blur
AlaskaAirlines/auro-interruption pull request #108
Opened 2023-11-08 16:34 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #107

## Summary:

This removes code that shouldn't have been added in the previous PR and updates the engine to Node 16

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-11-08 19:31 UTC, jordanjones243 approved these changes

2023-11-08 21:20 UTC, blackfalcon requested changes
Please update the commit title to be 50 characters or less.

2023-11-08 21:20 UTC, blackfalcon commented on package.json
> +    "node": ">=v16.19.0"
What is the reason for updating to Node 16? Testing is still targeting `test (11.x)", "test (12.x)", "test (14.x)"` and the publishing workflow is targeting `14.x`. 

Also, I am not seeing an updated package-lock.json update to support this?

2023-11-09 01:37 UTC, blackfalcon requested changes

2023-11-09 01:37 UTC, blackfalcon commented on src/component-base.js
> +    });
I see that the action failed and when I run this locally I get the following error

```
  auro-dialog
    ✖ auro-dialog is accessible
    ✔ auro-dialog is accessible
    ✔ auro-dialog custom element is defined
    ✔ auro-dialog custom element is defined
    ✔ auro-dialog dialog renders a close icon
    ✔ auro-dialog dialog renders a close icon
    ✔ auro-dialog renders only a close icon
    ✔ auro-dialog renders only a close icon
  ✖ "after each" hook
```
Then the CLI freezes.

2023-11-09 01:40 UTC, blackfalcon commented
@jason-capsule42 I recommend that you REVERT @fajar-apri-alaska MERGE and put that back into a working branch and then work on that branch to fix the issues with the build fail there. 

https://github.com/AlaskaAirlines/auro-interruption/pull/106

2023-11-09 09:47 UTC, fajar-apri-alaska commented on src/component-base.js
> +    });
> I see that the action failed and when I run this locally I get the following error
> 
> ```
>   auro-dialog
>     ✖ auro-dialog is accessible
>     ✔ auro-dialog is accessible
>     ✔ auro-dialog custom element is defined
>     ✔ auro-dialog custom element is defined
>     ✔ auro-dialog dialog renders a close icon
>     ✔ auro-dialog dialog renders a close icon
>     ✔ auro-dialog renders only a close icon
>     ✔ auro-dialog renders only a close icon
>   ✖ "after each" hook
> ```
> 
> Then the CLI freezes.

FYI the same error one also showing up in the master branch before #106 merge, at least in my local forked repo, I'm sure that something is wrong because it is repeating the test case like above logs, and also not sure why git action is passing the test.

in #106, my current solution was adding simple condition checks to that `lastFocusableElement` variable because I believe that `addEventListener` could somehow refer to `undefined` value (this is from my research when I found this issue).

I already inform @jason-capsule42 if that's a good enough solution because I'm not sure that would break the UX or anything. Although, there's other solution that by adding a `focusable` element in the `auro-dialog is accessible` test case like below:

<img width="730" alt="image" src="https://github.com/AlaskaAirlines/auro-interruption/assets/124668226/d066a0a5-5520-4f4b-a538-86a9f682fb7d">

That does pass the first test case. Although, there is another test case where it finally shows that `addEventListener` does find an `undefined`.
<img width="1118" alt="image" src="https://github.com/AlaskaAirlines/auro-interruption/assets/124668226/a79b94a8-f348-4941-a00f-9d97d45879f7">

2023-11-13 02:34 UTC, closed without merging