fix(popover): allow popover content to position correctly #109
AlaskaAirlines/auro-interruption pull request #110
Opened 2023-11-13 02:38 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #41

## Summary:

This PR implements style code fixes to keep popperJS bib content placed correctly when used in auro-dialog and drawer. Document examples were also added for dialog and drawer to demonstrate this.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-11-28 01:34 UTC, blackfalcon requested changes

2023-11-28 01:34 UTC, blackfalcon commented on demo/dialog.md
> +        <span slot="trigger" style="color: blue; text-decoration: underline;">Hover on me</span>
Let's not use `blue` as a color choice. For this example, we should use the correct token. 

Also, let's place it in the content of the dialog already there. Like, use the `specific itinerary chosen` string. No need to change the contents of the popover, but it looks like it belongs versus where it is now.

2023-11-28 01:34 UTC, blackfalcon commented on demo/drawer.md
> +        <span slot="trigger" style="color: blue; text-decoration: underline;">Hover on me</span>
Same comment from the dialog example.

2023-12-04 17:38 UTC, jason-capsule42 commented on demo/dialog.md
> +## Dialog with popover and dopdown components
I believe what @jordanjones243 means here is that the example should be using `auro-dropdown` rather than a plan popperJS example.

2023-12-14 00:26 UTC, jordanjones243 approved these changes

2023-12-14 18:01 UTC, merged

2023-12-14 20:21 UTC, AuroDesignSystem commented
:tada: This PR is included in version 1.4.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-interruption/v/1.4.5)
- [GitHub release](https://github.com/AlaskaAirlines/auro-interruption/releases/tag/v1.4.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: