docs: convert to modern doc system
AlaskaAirlines/auro-interruption pull request #24
Opened 2021-03-12 00:35 UTC by jason-capsule42

# Alaska Airlines Pull Request

**Fixes:** #21

## Summary:

Convert old react style docs to new format used in wc-generator.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-03-19 04:46 UTC, jason-capsule42 commented
@blackfalcon this is one of the two draft PRs that needed your input regarding how to integrate custom function calls and style imports for demo page example code blocks. Please let me know if you need additional information.

2021-03-20 16:29 UTC, blackfalcon commented
This is looking pretty good so far. You can delete `index_old.html` when you are done transferring the content. Also, please build the other `.html` files. Dialog and Drawer.

2021-03-20 16:37 UTC, blackfalcon requested changes

2021-03-20 16:37 UTC, blackfalcon commented on demo/index.html
> +    <script>
These functions should be abstracted into a single file that can be imported into the scope of the demos here and also be referenced in the demo page for the docsite.

2021-03-20 16:37 UTC, blackfalcon commented on demo/index_old.html
> +<!DOCTYPE html>
This file can be deleted once the new demo pages have been created.

2021-03-26 22:25 UTC, closed without merging