Remove tokens from final CSS output
AlaskaAirlines/auro-interruption pull request #32
Opened 2021-04-23 23:52 UTC by blackfalcon

# Alaska Airlines Pull Request

**Fixes:** #30 

## Summary:

This PR addresses a miss in the latest conversation from a legacy DX to a new DX with the interruptions component. 

This update was a miss in the review of the update that the little-used feature was removed from the repo. 

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Other (bug fix)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-04-26 16:29 UTC, geoffrich requested changes
I still see the custom properties being imported in the CSS files, so they're still included in the bundle.

2021-04-26 16:29 UTC, geoffrich commented on scripts/removeNonRemPlugin.js
> +    css.wa
Seems like something's missing here

2021-04-26 16:29 UTC, geoffrich commented on src/style-drawer.scss
> +@import "./node_modules/@alaskaairux/design-tokens/dist/tokens/SassCustomProperties";
Why is this being imported? This is the issue my bug report was meant to address -- we're importing all the custom property definitions, bloating the bundled output. I thought the user of the component was supposed to define the properties.

2021-04-26 16:56 UTC, blackfalcon commented on scripts/removeNonRemPlugin.js
> +    css.wa
O_O

2021-04-26 16:58 UTC, blackfalcon commented on src/style-drawer.scss
> +@import "./node_modules/@alaskaairux/design-tokens/dist/tokens/SassCustomProperties";
This is for the CSS custom properties fallback. The tokens need to be injected into the scope of the CSS file so that PostCSS can resolve the true value from the variable. 

There is a cleanup process in the PostCSS that deleted all those tokens from the final CSS that is in the package. 

The issue you brought was resolved as the PostCSS process was NOT deleting the tokens from the final CSS.

2021-04-26 16:59 UTC, blackfalcon commented on src/style-drawer.scss
> +@import "./node_modules/@alaskaairux/design-tokens/dist/tokens/SassCustomProperties";
This line was added as it was missed initially that it wasn't in the updates in the first place.

2021-04-26 17:11 UTC, geoffrich commented on src/style-drawer.scss
> +@import "./node_modules/@alaskaairux/design-tokens/dist/tokens/SassCustomProperties";
Okay, I wasn't aware of how the fallback worked. Looking at the component output in `dist/`, `style-drawer-fixed-css.js` still contains all the auro tokens. Is there away to remove them from that file as well?

2021-04-27 00:09 UTC, blackfalcon commented on src/style-drawer.scss
> +@import "./node_modules/@alaskaairux/design-tokens/dist/tokens/SassCustomProperties";
Here is the issue I am seeing. `style-drawer-fixed.scss` has no tokens. It's all absolute values. This breaks all expectations we have for running any of this process. 

So the task now is how to adjust that expectation?

2021-04-27 00:43 UTC, blackfalcon commented on src/style-drawer.scss
> +@import "./node_modules/@alaskaairux/design-tokens/dist/tokens/SassCustomProperties";
https://github.com/AlaskaAirlines/auro-interruption/pull/32/commits/078c3495720330d82501bfaed69e9b8cd892f84d

2021-04-27 14:57 UTC, geoffrich commented on src/style-drawer.scss
> +@import "./node_modules/@alaskaairux/design-tokens/dist/tokens/SassCustomProperties";
I guess that works? At least the tokens aren't there anymore.

2021-04-29 21:54 UTC, blackfalcon commented on scripts/removeNonRemPlugin.js
> +    css.wa
Remmoved. No impact in feature.

2021-04-29 23:05 UTC, geoffrich approved these changes

2021-04-30 00:12 UTC, merged

2021-04-30 00:15 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 1.2.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-interruption/v/1.2.4)
- [GitHub release](https://github.com/AlaskaAirlines/auro-interruption/releases/tag/v1.2.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: