add attribute stickyFooter to make the footer sticky
AlaskaAirlines/auro-interruption pull request #58
Opened 2021-11-18 21:10 UTC by BrentLabasan

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** # (issue, if applicable)

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [ ] My update follows the CONTRIBUTING guidelines of this project
- [ ] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2021-11-20 00:49 UTC, blackfalcon requested changes
Please review Auro's contributing guidelines and update the commit messages accordingly, http://auro.alaskaair.com/contributing#:~:text=Git%20commit%20messages

This PR is small enough, I'd prefer that this was squashed into a single commit about how it will add the `stickyFooter` attribute. 

Please update the commit message to reference the Github issue number, not ADO's. In the history there is no link between those individual ticketing systems. 

Also, please update the JSDoc in the head of the element's JS file so that this update is referenced in the API documentation. Also, please be sure to run either `npm run build` or `npm run apiBuild` to generate the automated docs.

2021-11-20 00:49 UTC, blackfalcon commented on src/style.scss
> +:host([stickyFooter]) {
I am not sure that creating an inset scrolling content window is the right way to address this. When applying this solution to the small dialog on mobile, you get the following issue. 

<img width="439" alt="Screen Shot 2021-11-19 at 4 16 18 PM" src="https://user-images.githubusercontent.com/181089/142706485-5673531b-3c45-4fa4-9846-66f333a70ea0.png">

If we did something like 

```scss
:host([stickyFooter]) {
  .dialog {
    padding-bottom: 0;
  }

  .dialog-footer {
    position: sticky;
    bottom: 0;
    background-color: var(--auro-color-base-white);
    padding: var(--auro-size-sm) 0 var(--auro-size-sm) 0;
  }
}
```

Then we will have this 

<img width="535" alt="Screen Shot 2021-11-19 at 4 38 51 PM" src="https://user-images.githubusercontent.com/181089/142707643-174cf538-05a3-4a31-8866-4fff464f38b8.png">

2021-11-20 00:49 UTC, blackfalcon commented on src/style.scss
> +  }
```suggestion
  .dialog {
    padding-bottom: 0;
  }

  .dialog-footer {
    position: sticky;
    bottom: 0;
    background-color: var(--auro-color-base-white);
    padding: var(--auro-size-sm) 0 var(--auro-size-sm) 0;
  }
```

2021-11-20 00:49 UTC, blackfalcon commented on demo/demo.md
> +If the height of the browser window is small, the user will have to scroll to the bottom of the modal to see the footer's content. If footer's content is very important, it could lead to lost revenue
Auro's content style guide is never speaking directly to business problems. The purpose of the API documentation is to speak to the features and API of the element. 

```suggestion
Use the `stickyFooter` attribute to fix the footer action buttons tolower part of the dialog window regardless of scroll position.
```

2021-11-20 00:49 UTC, blackfalcon commented on demo/demo.md
> +If the height of the browser window is small, the user will have to scroll to the bottom of the modal to see the footer's content. If footer's content is very important, it could lead to lost revenue
This demo needs to be added to the `.demo/dialog.md` as well.

2021-11-22 23:24 UTC, BrentLabasan commented on demo/demo.md
> +If the height of the browser window is small, the user will have to scroll to the bottom of the modal to see the footer's content. If footer's content is very important, it could lead to lost revenue
Changed the text.

2021-11-22 23:27 UTC, BrentLabasan commented on src/style.scss
> +  }
Switched the CSS to the suggested CSS.

2021-11-23 05:15 UTC, closed without merging