fix(util): keeping the modal tabbing inside the focus area #90
AlaskaAirlines/auro-interruption pull request #92
Opened 2022-10-27 23:40 UTC by jesussilverioea

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #90 

## Summary:

Currently, there is an issue when setting up the inert of the children when the component is inside another shadowDOM and the user starts tabbing and getting out of the focus zone.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [X] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [X] My update follows the CONTRIBUTING guidelines of this project
- [X] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-10-27 23:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AlaskaAirlines/auro-interruption?pullRequest=92) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AlaskaAirlines/auro-interruption?pullRequest=92) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AlaskaAirlines/auro-interruption?pullRequest=92) it.</sub>

2022-10-28 16:29 UTC, blackfalcon requested changes

2022-10-28 16:29 UTC, blackfalcon commented on src/util.js
> +		}
nit-pick

Not sure what happened to the tabbing here, but please correct the code formatting.

2022-10-28 16:30 UTC, blackfalcon commented
Please adjust the commit message. See https://auro.alaskaair.com/contributing#:~:text=BREAKING%20CHANGE%20comment.-,Git%20commit%20messages,-Once%20you%20have for proper formatting.

2022-10-28 18:07 UTC, jesussilverioea commented on src/util.js
> +		}
right formatting has been apply 👍

2022-11-02 22:06 UTC, blackfalcon approved these changes

2022-11-02 22:07 UTC, merged

2022-11-02 22:10 UTC, AuroDesignSystem commented
:tada: This PR is included in version 1.4.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-interruption/v/1.4.2)
- [GitHub release](https://github.com/AlaskaAirlines/auro-interruption/releases/tag/v1.4.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: